_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 76
                - 77
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 76
                - 77
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.10
            "6": 4.50.3
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
ablation_state:
    value: 0
ablation_study:
    value: 0
activation:
    value: relu
add_self_loop:
    value: true
city:
    value: CHI
cuda:
    value: "0"
epochs:
    value: 10000
input_dim:
    value: 64
lam_1:
    value: 1
lam_2:
    value: 2
lam_3:
    value: 3
layer_norm:
    value: false
lr:
    value: 0.0001
manifold_name:
    value: poincare
model_name:
    value: H3GNN
multi_cuda:
    value: 0
negative_K:
    value: 4
nhead:
    value: 3
nhid:
    value: 256
out_dim:
    value: 384
out_nhead:
    value: 3
poi_class_number:
    value: 273
poi_number:
    value: 5807
seed:
    value: 1
split:
    value: 0.8
time_point_number:
    value: 770
user_number:
    value: 6444
wd:
    value: 1e-10
